<!-- SPDX-License-Identifier: AGPL-3.0-or-later -->
<script lang="ts">
	import '$lib/styles/docs.css';
	import DocsHeader from '$lib/components/DocsHeader.svelte';

	const pageTitle = 'ULS Reinforcement Output — MADEP CPT Interpreter';
	const pageDescription =
		'Technical engineering chapter for the Stage 6 reinforcement output: strip-moment handoff, EC2 strain-compatibility derivation, implemented mu-omega closed form, durability-cover algorithm, bar-spacing translation, and modelling limits.';
	const canonicalUrl = 'https://cpt.madep.be/docs/engineering/reinforcement';
	const ogImageUrl = 'https://cpt.madep.be/logo.png';
</script>

<svelte:head>
	<title>{pageTitle}</title>
	<meta name="description" content={pageDescription} />
	<link rel="canonical" href={canonicalUrl} />
	<meta property="og:title" content={pageTitle} />
	<meta property="og:description" content={pageDescription} />
	<meta property="og:type" content="article" />
	<meta property="og:url" content={canonicalUrl} />
	<meta property="og:image" content={ogImageUrl} />
</svelte:head>

<div class="docs-page">
	<DocsHeader />

	<header class="hero hero--compact">
		<div class="hero__inner">
			<p class="hero__eyebrow">Stage 6 / reinforcement output</p>
			<h1>ULS reinforcement output.</h1>
			<p class="hero__lead">
				The reinforcement route converts the ULS bending moment from the strip-on-foundation solve
				into a required area of tension reinforcement per meter width, using EC2 strain
				compatibility on the parabola–rectangle concrete law and an elastic–perfectly-plastic steel
				law. The derivation below is the screening-level theory backing that output.
			</p>
		</div>
	</header>

	<div class="docs-shell">
		<aside class="docs-nav" aria-label="Reinforcement documentation navigation">
			<div class="docs-nav__title">Reinforcement</div>
			<a href="#scope">Scope and intent</a>
			<a href="#solverlink">Strip result to section check</a>
			<a href="#hsensitivity">A<sub>s,req</sub> sensitivity to h on Winkler</a>
			<a href="#kinematics">Kinematics and constitutive laws</a>
			<a href="#block">Rectangular stress block</a>
			<a href="#route">Dimensionless route (μ, ω)</a>
			<a href="#ductility">Ductility and double reinforcement</a>
			<a href="#minmax">Minimum and maximum steel</a>
			<a href="#shear">Shear screening</a>
			<a href="#materials">Material factors, cover, exposure</a>
			<a href="#spacing">From A<sub>s</sub> to bars</a>
			<a href="#outputs">Outputs and limitations</a>
			<a href="#references">References</a>
		</aside>

		<main class="docs-content">
			<section id="scope" class="doc-card">
				<p class="section-label">Scope and intent</p>
				<h2>1. Problem class and meaning of the result</h2>
				<p>
					The reinforcement route is a <strong>strip ULS reinforcement screen</strong>. It takes the
					design bending moment per meter of strip width that the beam-on-foundation solver reports
					and returns the tension reinforcement area required to develop that moment, assuming a
					singly reinforced rectangular section and EC2 material laws.
				</p>
				<div class="doc-callout">
					<strong>Scope boundary.</strong> The result is a <em>one-dimensional strip</em>
					reinforcement quantity. It does not produce a two-dimensional bar layout, does not size
					shear links, does not verify serviceability crack widths or deflections, and does not
					account for punching at column heads. It is a preliminary sizing screen that the engineer
					then carries into a dedicated structural design tool.
				</div>
				<div class="symbols">
					<div class="symbols__title">Primary quantities</div>
					<dl class="symbols__list">
						<div class="symbols__row">
							<dt>M<sub>Ed</sub></dt>
							<dd>Design bending moment for the modelled strip width; this is kN·m/m when b = 1.0 m.</dd>
						</div>
						<div class="symbols__row">
							<dt>A<sub>s,req</sub></dt>
							<dd>Required tension reinforcement area for the modelled strip width; this is mm²/m when b = 1.0 m.</dd>
						</div>
						<div class="symbols__row">
							<dt>μ, ω</dt>
							<dd>Dimensionless bending moment and mechanical reinforcement ratio [-].</dd>
						</div>
						<div class="symbols__row">
							<dt>ξ<sub>lim</sub></dt>
							<dd>Limiting neutral-axis ratio for tension-controlled (ductile) failure [-].</dd>
						</div>
					</dl>
				</div>
			</section>

			<section id="solverlink" class="doc-card">
				<p class="section-label">Strip to section handoff</p>
				<h2>2. From the strip-on-foundation solve to the reinforced-concrete section check</h2>
				<p>
					The reinforcement route does not start from a free structural load model. It starts from
					the <strong>ULS bending-moment envelope generated by the Stage 6 strip solver</strong>.
					The current implementation takes the absolute governing bending moment per meter strip
					width, converts the geometric inputs to the modelled strip width, derives the effective
					depth from the EC2 cover route, and then performs a singly reinforced rectangular-section
					check. For normal slab-strip screening this is a 1000 mm strip; for an actual beam or
					strip foundation it follows the entered beam/strip width b.
				</p>
				<div class="doc-callout">
					<strong>Why A<sub>s,req</sub> can rise with h.</strong> In a standalone RC section
					check, increasing h at fixed M<sub>Ed</sub> increases d and would normally reduce
					A<sub>s,req</sub>. In this app M<sub>Ed</sub> is recalculated by the
					beam-on-foundation solver after h changes. If the stiffer strip develops a larger
					moment, that moment increase can outweigh the larger effective depth.
				</div>
				<div class="equations">
					<div class="formula">M<sub>Ed</sub> = |M<sub>ULS,max</sub>|</div>
					<div class="formula">b<sub>w</sub> = 1000 b    (modelled strip width in mm)</div>
					<div class="formula">h<sub>mm</sub> = 1000 h</div>
					<div class="formula">d = h<sub>mm</sub> − c<sub>nom</sub> − φ<sub>bar</sub>/2</div>
					<div class="formula">f<sub>cd</sub> = f<sub>ck</sub>/γ<sub>C</sub>,   f<sub>yd</sub> = f<sub>yk</sub>/γ<sub>S</sub></div>
					<div class="formula">μ = M<sub>Ed</sub> · 10<sup>6</sup> / (b<sub>w</sub> d<sup>2</sup> f<sub>cd</sub>)</div>
					<div class="formula">ω = 1 − √(1 − 2μ)    for the current public screen</div>
					<div class="formula">A<sub>s,req</sub> = ω b<sub>w</sub> d f<sub>cd</sub> / f<sub>yd</sub></div>
					<div class="formula">A<sub>s</sub> = max(A<sub>s,req</sub>, A<sub>s,min</sub>)</div>
				</div>
				<div class="symbols">
					<div class="symbols__title">Implemented handoff quantities</div>
					<dl class="symbols__list">
						<div class="symbols__row">
							<dt>M<sub>ULS,max</sub></dt>
							<dd>Maximum bending moment reported by the strip analysis under the selected ULS combination [kN·m/m].</dd>
						</div>
						<div class="symbols__row">
							<dt>h</dt>
							<dd>Member thickness as entered in Stage 6 [m]. Internally converted to millimetres for the section check.</dd>
						</div>
						<div class="symbols__row">
							<dt>c<sub>nom</sub></dt>
							<dd>Nominal cover returned by the EC2 durability route [mm].</dd>
						</div>
						<div class="symbols__row">
							<dt>φ<sub>bar</sub></dt>
							<dd>Selected bar diameter [mm]. In the current implementation no separate stirrup or link diameter is deducted from d.</dd>
						</div>
					</dl>
				</div>
				<ul class="notes">
					<li>The current public result is based on <strong>the absolute governing moment only</strong>. It is therefore a required steel magnitude, not yet a separate top-versus-bottom reinforcement map.</li>
					<li>The current implementation uses f<sub>cd</sub> = f<sub>ck</sub>/γ<sub>C</sub>. In Belgian practice this is equivalent to taking α<sub>cc</sub> = 1.0 in the EC2 reduction route.</li>
					<li>With b = 1.0 m, the section width is one meter of strip and A<sub>s</sub> is reported in mm²/m. With b different from 1.0 m, A<sub>s</sub> is the total area for the modelled strip width.</li>
				</ul>
			</section>

			<section id="hsensitivity" class="doc-card">
				<p class="section-label">Sensitivity to member depth</p>
				<h2>3. Effect of the strip depth h on A<sub>s,req</sub> (Winkler strip)</h2>
				<p>
					On a rigid-support beam M is fixed by statics, so increasing h reduces μ and reduces
					A<sub>s,req</sub> monotonically. On a Winkler foundation that intuition fails: the
					moment is not given by statics. EI grows as h<sup>3</sup>, λ grows as h<sup>13/16</sup>,
					and the peak moment grows along with λ. Whether A<sub>s,req</sub> increases or decreases
					with h is decided by which power of h dominates: the moment increase or the lever-arm
					gain.
				</p>
				<div class="equations">
					<div class="formula">EI ∝ h<sup>3</sup>,   k<sub>s</sub> ∝ h<sup>−1/4</sup>   (Vesić soft coupling)</div>
					<div class="formula">λ = (4 EI/(b k<sub>s</sub>))<sup>1/4</sup> ∝ h<sup>13/16</sup> ≈ h<sup>0.81</sup></div>
					<div class="formula">d ≈ h − constant ⇒ d ∝ h</div>
					<div class="formula">μ = M<sub>Ed</sub> · 10<sup>6</sup> / (b<sub>w</sub> d<sup>2</sup> f<sub>cd</sub>),   ω ≈ μ for small μ</div>
					<div class="formula">A<sub>s,req</sub> = ω b<sub>w</sub> d f<sub>cd</sub>/f<sub>yd</sub> ≈ M<sub>Ed</sub>/(d f<sub>yd</sub>) for small μ</div>
				</div>
				<p>
					The Hetényi closed forms in <a href="/docs/engineering/beam#hsensitivity">the beam
					chapter §6</a> give M<sub>Ed</sub>(h) for each canonical load case. Carrying those
					exponents through the small-μ approximation A<sub>s,req</sub> ≈ M<sub>Ed</sub>/(d
					f<sub>yd</sub>):
				</p>
				<div class="doc-table-wrap">
					<p class="doc-table-caption">Direction of A<sub>s,req</sub>(h) sensitivity by load case in the small-μ regime.</p>
					<div class="doc-table-scroll">
						<table class="doc-table">
							<thead>
								<tr>
									<th>Load case</th>
									<th>M<sub>Ed</sub> ∝ h<sup>α</sup></th>
									<th>A<sub>s,req</sub> ∝ h<sup>α−1</sup></th>
									<th>Effect of growing h</th>
								</tr>
							</thead>
							<tbody>
								<tr>
									<td>Concentrated load (point or short patch)</td>
									<td>h<sup>0.81</sup></td>
									<td>h<sup>−0.19</sup></td>
									<td>A<sub>s,req</sub> decreases slowly</td>
								</tr>
								<tr>
									<td>Patch UDL (L<sub>patch</sub> &lt; λ)</td>
									<td>h<sup>1.63</sup></td>
									<td>h<sup>0.63</sup></td>
									<td><strong>A<sub>s,req</sub> increases with h</strong></td>
								</tr>
								<tr>
									<td>Full-strip UDL on free-ended strip</td>
									<td>≈ 0</td>
									<td>≈ 0</td>
									<td>A<sub>s,req</sub> hits A<sub>s,min</sub> floor</td>
								</tr>
							</tbody>
						</table>
					</div>
					<p class="doc-table-note">Crossover at α = 1: any load case where the strip-on-foundation solver returns M<sub>Ed</sub> growing faster than h<sup>1</sup> drives A<sub>s,req</sub> upward with h. The patch-UDL case crosses that boundary; the point-load case does not.</p>
				</div>
				<div class="doc-callout">
					<strong>Worked illustration.</strong> Patch UDL load case, b = 1 m, f<sub>ck</sub> = 30
					MPa, c<sub>nom</sub> + φ<sub>bar</sub>/2 = 36 mm, M<sub>Ed,1</sub> = 100 kN·m at
					h<sub>1</sub> = 0.30 m. Going to h<sub>2</sub> = 0.50 m: M<sub>2</sub>/M<sub>1</sub> =
					(0.5/0.3)<sup>1.63</sup> ≈ 2.15, M<sub>Ed,2</sub> ≈ 215 kN·m, d<sub>1</sub> = 264 mm,
					d<sub>2</sub> = 464 mm; μ<sub>1</sub> = 0.072 → A<sub>s,1</sub> ≈ 904 mm²/m,
					μ<sub>2</sub> = 0.050 → A<sub>s,2</sub> ≈ 1094 mm²/m. The +21% jump in A<sub>s</sub>
					comes entirely from the foundation interaction; the section check is unchanged.
				</div>
				<ul class="notes">
					<li>This is a property of the soil-supported analysis, not of the EC2 section check. The μ–ω–A<sub>s</sub> relationship in §5 is monotonic; what changes is the M<sub>Ed</sub> input that the strip solver delivers.</li>
					<li>The closed-form scalings are exact in the small-μ limit (ω ≈ μ). For μ approaching the ductility bound μ<sub>lim</sub> ≈ 0.372 the relationship saturates, but the qualitative direction is preserved.</li>
					<li>If M<sub>Ed</sub> is taken from an external structural model rather than the Stage 6 strip solver, the conventional intuition (more h → less A<sub>s</sub>) does apply. The two checks are separate problems and should be kept separate in the audit trail.</li>
					<li>The same logic applies inversely to k<sub>s</sub>: stiffening the soil column reduces λ and reduces M<sub>Ed</sub> for the patch-UDL case, lowering A<sub>s,req</sub> ∝ k<sub>s</sub><sup>−1/2</sup>.</li>
				</ul>
			</section>

			<section id="kinematics" class="doc-card">
				<p class="section-label">Kinematics and constitutive laws</p>
				<h2>4. Plane sections, concrete law, and steel law</h2>
				<p>
					The formulation is the standard EC2 ULS bending assumption for reinforced concrete:
					plane sections remain plane, strain varies linearly through the depth, concrete
					in tension is ignored, and steel and concrete are each represented by an idealized
					constitutive law.
				</p>
				<div class="equations">
					<div class="formula">ε(y) = ε<sub>c</sub>(y<sub>top</sub> − y)/x linear strain profile</div>
					<div class="formula">σ<sub>c</sub>(ε<sub>c</sub>) = f<sub>cd</sub>[1 − (1 − ε<sub>c</sub>/ε<sub>c2</sub>)<sup>n</sup>]  for 0 ≤ ε<sub>c</sub> ≤ ε<sub>c2</sub></div>
					<div class="formula">σ<sub>c</sub>(ε<sub>c</sub>) = f<sub>cd</sub>                         for ε<sub>c2</sub> ≤ ε<sub>c</sub> ≤ ε<sub>cu2</sub></div>
					<div class="formula">n = 2,   ε<sub>c2</sub> = 2.0‰,   ε<sub>cu2</sub> = 3.5‰  (f<sub>ck</sub> ≤ 50 MPa)</div>
					<div class="formula">ε<sub>s</sub> = ε<sub>cu2</sub>(d − x)/x     at the tension steel level</div>
					<div class="formula">σ<sub>s</sub>(ε<sub>s</sub>) = E<sub>s</sub> ε<sub>s</sub>  for |ε<sub>s</sub>| ≤ f<sub>yd</sub>/E<sub>s</sub></div>
					<div class="formula">σ<sub>s</sub>(ε<sub>s</sub>) = sign(ε<sub>s</sub>) · f<sub>yd</sub>     beyond yield (horizontal branch adopted)</div>
					<div class="formula">EC2 general form: f<sub>cd</sub> = α<sub>cc</sub> f<sub>ck</sub>/γ<sub>C</sub>,   f<sub>yd</sub> = f<sub>yk</sub>/γ<sub>S</sub></div>
					<div class="formula">Current public implementation: f<sub>cd</sub> = f<sub>ck</sub>/γ<sub>C</sub>,   f<sub>yd</sub> = f<sub>yk</sub>/γ<sub>S</sub></div>
				</div>
				<div class="symbols">
					<div class="symbols__title">Notation</div>
					<dl class="symbols__list">
						<div class="symbols__row">
							<dt>ε<sub>c</sub>, ε<sub>c2</sub>, ε<sub>cu2</sub></dt>
							<dd>Concrete compressive strain, strain at peak, and ultimate strain [-]. Values for f<sub>ck</sub> ≤ 50 MPa.</dd>
						</div>
						<div class="symbols__row">
							<dt>n</dt>
							<dd>Exponent of the parabolic branch (n = 2 for normal strength).</dd>
						</div>
						<div class="symbols__row">
							<dt>x</dt>
							<dd>Neutral-axis depth from the compressed fibre [m].</dd>
						</div>
						<div class="symbols__row">
							<dt>ε<sub>s</sub></dt>
							<dd>Tension-steel strain obtained from the strain triangle at depth d.</dd>
						</div>
						<div class="symbols__row">
							<dt>E<sub>s</sub></dt>
							<dd>Steel Young modulus, 200 GPa.</dd>
						</div>
						<div class="symbols__row">
							<dt>α<sub>cc</sub></dt>
							<dd>Sustained-load coefficient. The current public route is consistent with α<sub>cc</sub> = 1.0.</dd>
						</div>
						<div class="symbols__row">
							<dt>γ<sub>C</sub>, γ<sub>S</sub></dt>
							<dd>Partial material factors for concrete and steel. Default ULS: γ<sub>C</sub> = 1.50, γ<sub>S</sub> = 1.15.</dd>
						</div>
					</dl>
				</div>
			</section>

			<section id="block" class="doc-card">
				<p class="section-label">Rectangular stress block</p>
				<h2>5. Equivalent rectangular block and its λ, η factors</h2>
				<p>
					Integrating the parabola–rectangle law across the compression zone and equating force and
					moment to an equivalent uniform block of depth λx and intensity η f<sub>cd</sub> produces
					the EC2 rectangular block with λ = 0.8 and η = 1.0 for normal-strength concrete. The
					factors retain the same resultant force and lever arm as the exact integral.
				</p>
				<div class="equations">
					<div class="formula">C<sub>c</sub> = ∫<sub>0</sub><sup>x</sup> σ<sub>c</sub>(ε(y)) b dy = η f<sub>cd</sub> b λ x</div>
					<div class="formula">ȳ<sub>c</sub> = ∫ σ<sub>c</sub> y b dy / C<sub>c</sub> = λx / 2   (by construction)</div>
					<div class="formula">λ = 0.8,   η = 1.0       for f<sub>ck</sub> ≤ 50 MPa</div>
					<div class="formula">λ = 0.8 − (f<sub>ck</sub> − 50)/400,   η = 1.0 − (f<sub>ck</sub> − 50)/200  for 50 &lt; f<sub>ck</sub> ≤ 90 MPa</div>
				</div>
				<div class="symbols">
					<div class="symbols__title">Notation</div>
					<dl class="symbols__list">
						<div class="symbols__row">
							<dt>C<sub>c</sub></dt>
							<dd>Resultant concrete compressive force per meter of strip [kN/m].</dd>
						</div>
						<div class="symbols__row">
							<dt>λ</dt>
							<dd>Reduced depth factor for the equivalent stress block.</dd>
						</div>
						<div class="symbols__row">
							<dt>η</dt>
							<dd>Reduced intensity factor (η = 1.0 for normal strength; &lt; 1 for high strength).</dd>
						</div>
					</dl>
				</div>
			</section>

			<section id="route" class="doc-card">
				<p class="section-label">Design route</p>
				<h2>6. Dimensionless moment μ and mechanical ratio ω</h2>
				<p>
					The closed-form route for a singly reinforced rectangular section drops out of equilibrium
					and the rectangular stress block. Denote the normalized moment
					μ = M<sub>Ed</sub>/(b d² f<sub>cd</sub>) and the mechanical reinforcement ratio
					ω = A<sub>s</sub> f<sub>yd</sub>/(b d f<sub>cd</sub>). Axial equilibrium gives
					ω = η λ ξ with ξ = x/d, and moment equilibrium about the tension bars yields a quadratic
					in ω whose tension-controlled solution is the classical closed form.
				</p>
				<div class="equations">
					<div class="formula">μ = M<sub>Ed</sub> / (b d² f<sub>cd</sub>)</div>
					<div class="formula">N = 0:  A<sub>s</sub> f<sub>yd</sub> = η f<sub>cd</sub> b λ x   ⇒   ω = η λ ξ</div>
					<div class="formula">M<sub>Rd</sub> about tension steel:   M<sub>Rd</sub> = η f<sub>cd</sub> b λ x (d − λx/2)</div>
					<div class="formula">General closed form:   μ = ω (1 − ω/(2η))    ⇒    ω = η [1 − √(1 − 2μ/η)]</div>
					<div class="formula">Current public route:   ω = 1 − √(1 − 2μ)</div>
					<div class="formula">A<sub>s,req</sub> = ω b d f<sub>cd</sub> / f<sub>yd</sub></div>
				</div>
				<div class="symbols">
					<div class="symbols__title">Notation</div>
					<dl class="symbols__list">
						<div class="symbols__row">
							<dt>h, c<sub>nom</sub>, φ<sub>bar</sub>, d</dt>
							<dd>Section thickness, nominal cover, tension-bar diameter, and effective depth [mm]. The current implementation does not subtract a separate link diameter.</dd>
						</div>
						<div class="symbols__row">
							<dt>b</dt>
							<dd>Reference width used in the section check (1000 mm per metre of strip).</dd>
						</div>
						<div class="symbols__row">
							<dt>ξ = x/d</dt>
							<dd>Relative neutral-axis depth.</dd>
						</div>
						<div class="symbols__row">
							<dt>M<sub>Rd</sub></dt>
							<dd>Section design moment resistance [kN·m/m].</dd>
						</div>
					</dl>
				</div>
				<p>
					The closed-form ω = η[1 − √(1 − 2μ/η)] is the tension-controlled root: the steel yields
					before the concrete crushes, so σ<sub>s</sub> = f<sub>yd</sub> is the right assumption.
					The alternative compression-controlled root would require a brittle-failure
					interpretation and is excluded by the ductility bound below.
				</p>
				<div class="doc-callout">
					<strong>Implementation note.</strong> The shipped Stage 6 screen currently uses the
					normal-strength shortcut ω = 1 − √(1 − 2μ) directly. It therefore does not yet carry the
					high-strength η reduction through the flexural closed form even though the documentation
					keeps the general EC2 expression visible for reference.
				</div>
			</section>

			<section id="ductility" class="doc-card">
				<p class="section-label">Ductility bound</p>
				<h2>7. Limiting neutral-axis depth and the case for compression steel</h2>
				<p>
					The closed form is only valid while steel yields before concrete crushes
					(ε<sub>s</sub> ≥ f<sub>yd</sub>/E<sub>s</sub> at ε<sub>c</sub> = ε<sub>cu2</sub>). Linear
					strain compatibility translates this into a limit on ξ; above that limit the section is
					over-reinforced and the rectangular block overestimates capacity unless compression
					reinforcement is introduced.
				</p>
				<div class="equations">
					<div class="formula">ε<sub>s,min</sub> = f<sub>yd</sub>/E<sub>s</sub></div>
					<div class="formula">ξ<sub>lim</sub> = ε<sub>cu2</sub> / (ε<sub>cu2</sub> + ε<sub>s,min</sub>)</div>
					<div class="formula">For B500B, f<sub>yd</sub> = 435 MPa, E<sub>s</sub> = 200 GPa:  ε<sub>s,min</sub> ≈ 2.175‰</div>
					<div class="formula">Pure compatibility upper bound:   ξ<sub>lim</sub> ≈ 0.617,   ω<sub>lim</sub> = η λ ξ<sub>lim</sub> ≈ 0.494</div>
					<div class="formula">Current public warning threshold:   μ ≳ 0.295   ⇒   redesign or move to a dedicated double-reinforcement check</div>
					<div class="formula">For a doubly reinforced section, general equilibrium becomes   A<sub>s</sub> f<sub>yd</sub> = C<sub>c</sub> + A′<sub>s</sub> σ′<sub>s</sub></div>
					<div class="formula">M<sub>Rd</sub> = C<sub>c</sub> z<sub>c</sub> + A′<sub>s</sub> σ′<sub>s</sub>(d − d′)</div>
				</div>
				<ul class="notes">
					<li>The app currently warns once μ exceeds about 0.295. That is the practical singly reinforced screen used by the public route, and it is stricter than the algebraic upper bound of the closed form.</li>
					<li>Once the warning is triggered, the engineer should increase h, change the material class, or move to a full doubly reinforced section design with explicit compression steel A′<sub>s</sub>.</li>
					<li>The public app does not yet size A′<sub>s</sub> automatically. It reports the flexural demand and warns that the singly reinforced shortcut is no longer the right design model.</li>
					<li>Tension-controlled failure is the default EC2 design target because it gives warning by cracking and deflection before collapse.</li>
				</ul>
			</section>

			<section id="minmax" class="doc-card">
				<p class="section-label">Detailing bounds</p>
				<h2>8. Minimum and maximum reinforcement area</h2>
				<p>
					Strain compatibility only sets the <em>required</em> area for the given moment. EC2
					detailing rules then impose a minimum and a maximum. The minimum protects against brittle
					cracking under the tensile capacity that the gross uncracked section can sustain; the
					maximum protects against congestion and compression-controlled behaviour.
				</p>
				<div class="equations">
					<div class="formula">A<sub>s,min</sub> = max(0.26 f<sub>ctm</sub>/f<sub>yk</sub> b<sub>t</sub> d,   0.0013 b<sub>t</sub> d)</div>
					<div class="formula">Current public route:   f<sub>ctm</sub> = 0.30 f<sub>ck</sub><sup>2/3</sup></div>
					<div class="formula">A<sub>s,max</sub> = 0.04 A<sub>c</sub> (outside lap zones)</div>
					<div class="formula">A<sub>s,eff</sub> = max(A<sub>s,req</sub>, A<sub>s,min</sub>)</div>
				</div>
				<div class="symbols">
					<div class="symbols__title">Notation</div>
					<dl class="symbols__list">
						<div class="symbols__row">
							<dt>f<sub>ctm</sub></dt>
							<dd>Mean axial tensile strength of concrete [MPa].</dd>
						</div>
						<div class="symbols__row">
							<dt>f<sub>cm</sub></dt>
							<dd>Mean compressive cylinder strength, f<sub>cm</sub> = f<sub>ck</sub> + 8 MPa. Useful for the full EC2 tensile-strength branch, though the current public route keeps the normal-strength f<sub>ctm</sub> expression.</dd>
						</div>
						<div class="symbols__row">
							<dt>b<sub>t</sub></dt>
							<dd>Width of the tension zone of the section (b for a rectangular strip).</dd>
						</div>
						<div class="symbols__row">
							<dt>A<sub>c</sub></dt>
							<dd>Cross-sectional area of concrete (b·h per meter of strip).</dd>
						</div>
					</dl>
				</div>
				<ul class="notes">
					<li>For typical slab-on-ground strip problems with moderate moment, A<sub>s,min</sub> frequently governs in the span fields and away from local peaks.</li>
					<li>The app reports both A<sub>s,req</sub> and the governing design area A<sub>s</sub> = max(A<sub>s,req</sub>, A<sub>s,min</sub>).</li>
					<li>The high-strength EC2 f<sub>ctm</sub> branch is not yet split out separately in the current screen, so high-strength concrete should be rechecked downstream in the structural workflow.</li>
				</ul>
			</section>

			<section id="shear" class="doc-card">
				<p class="section-label">Shear screening</p>
				<h2>9. Shear capacity without stirrups (V<sub>Rd,c</sub>)</h2>
				<p>
					The reinforcement output is a flexural quantity, but shear almost always governs detailing
					for thin slab strips on elastic foundation. The EC2 empirical expression for
					members without shear reinforcement is included here for continuity; the engineer runs it
					against the V<sub>Ed</sub> envelope from the beam solver.
				</p>
				<div class="equations">
					<div class="formula">V<sub>Rd,c</sub> = [C<sub>Rd,c</sub> k (100 ρ<sub>l</sub> f<sub>ck</sub>)<sup>1/3</sup> + k<sub>1</sub> σ<sub>cp</sub>] b<sub>w</sub> d</div>
					<div class="formula">V<sub>Rd,c,min</sub> = (v<sub>min</sub> + k<sub>1</sub> σ<sub>cp</sub>) b<sub>w</sub> d</div>
					<div class="formula">k = min(1 + √(200/d[mm]),  2.0)</div>
					<div class="formula">ρ<sub>l</sub> = min(A<sub>sl</sub>/(b<sub>w</sub> d),  0.02)</div>
					<div class="formula">C<sub>Rd,c</sub> = 0.18/γ<sub>C</sub>,   k<sub>1</sub> = 0.15,   v<sub>min</sub> = 0.035 k<sup>3/2</sup> f<sub>ck</sub><sup>1/2</sup></div>
				</div>
				<div class="symbols">
					<div class="symbols__title">Notation</div>
					<dl class="symbols__list">
						<div class="symbols__row">
							<dt>ρ<sub>l</sub></dt>
							<dd>Longitudinal reinforcement ratio using the tension steel anchored past the section.</dd>
						</div>
						<div class="symbols__row">
							<dt>k</dt>
							<dd>Size-effect factor capped at 2.0.</dd>
						</div>
						<div class="symbols__row">
							<dt>σ<sub>cp</sub></dt>
							<dd>Mean compressive stress from axial load (taken positive) [MPa]. Zero for an unprestressed slab strip.</dd>
						</div>
						<div class="symbols__row">
							<dt>b<sub>w</sub></dt>
							<dd>Minimum web width at the shear section (equal to b for a slab strip).</dd>
						</div>
					</dl>
				</div>
				<ul class="notes">
					<li>If V<sub>Ed</sub> &gt; V<sub>Rd,c</sub>, the section needs shear reinforcement; that is outside the reinforcement-screen route.</li>
					<li>Size effect k is meaningful for thin slabs because d is in the denominator of the √(200/d) term.</li>
				</ul>
			</section>

			<section id="materials" class="doc-card">
				<p class="section-label">Material and detailing assumptions</p>
				<h2>10. Material factors, structural class, and the implemented EC2 cover route</h2>
				<p>
					The route applies EC2 partial factors and derives the effective depth from the geometric
					inputs. Concrete cover is built from the exposure class, concrete class, and design
					working life per EC2 §4.4.1. The resulting c<sub>nom</sub> feeds directly into the
					effective depth, so durability assumptions influence both the stiffness-compatible
					reinforcement demand and the practical steel area that can be placed.
				</p>
				<div class="equations">
					<div class="formula">S = clamp(4 + ΔS<sub>life</sub> − ΔS<sub>hs</sub> − ΔS<sub>slab</sub> − ΔS<sub>QC</sub>, 1, 6)</div>
					<div class="formula">ΔS<sub>life</sub> = +2 for 100-year working life,   −1 for ≤ 25 years,   0 otherwise</div>
					<div class="formula">ΔS<sub>hs</sub> = 1 when f<sub>ck</sub> reaches the exposure-dependent high-strength threshold</div>
					<div class="formula">c<sub>min,b</sub> = max(φ<sub>bar</sub>, 6 mm) + 5 mm if d<sub>G</sub> &gt; 32 mm</div>
					<div class="formula">c<sub>min</sub> = max(c<sub>min,dur</sub>, c<sub>min,b</sub>, 10 mm)</div>
					<div class="formula">c<sub>nom,raw</sub> = max(c<sub>min</sub> + Δc<sub>dev</sub> + Δc<sub>uneven</sub>, c<sub>floor</sub>)</div>
					<div class="formula">c<sub>nom,recommended</sub> = 5 · ceil(c<sub>nom,raw</sub>/5)</div>
					<div class="formula">c<sub>nom,used</sub> = c<sub>nom,override</sub>   or   c<sub>nom,recommended</sub> when no override is given</div>
				</div>
				<div class="symbols">
					<div class="symbols__title">Notation</div>
					<dl class="symbols__list">
						<div class="symbols__row">
							<dt>c<sub>min,b</sub></dt>
							<dd>Minimum cover for bond, equal to bar diameter.</dd>
						</div>
						<div class="symbols__row">
							<dt>c<sub>min,dur</sub></dt>
							<dd>Minimum cover for durability, from EC2 Table 4.4N using the derived structural class S and the relevant exposure column.</dd>
						</div>
						<div class="symbols__row">
							<dt>Δc<sub>dev</sub></dt>
							<dd>Allowance for execution deviation (EC2 §4.4.1.3).</dd>
						</div>
						<div class="symbols__row">
							<dt>d<sub>G</sub></dt>
							<dd>Maximum aggregate size [mm]. The current route adds 5 mm to c<sub>min,b</sub> if d<sub>G</sub> &gt; 32 mm.</dd>
						</div>
						<div class="symbols__row">
							<dt>c<sub>floor</sub></dt>
							<dd>Minimum cover floor from ground casting assumptions: 40 mm for prepared ground, 75 mm for unprepared ground.</dd>
						</div>
					</dl>
				</div>
				<ul class="notes">
					<li>Exposure fallbacks used by the current app are explicit: XF1/XF2/XF3 and XA1/XA2 map to the XC4 corrosion-cover column; XF4 and XA3 map to XD3.</li>
					<li>The automatic structural-class route starts from S = 4, then adjusts for working life, high-strength concrete, slab-like geometry, and special quality control.</li>
					<li>Common ULS defaults are γ<sub>C</sub> = 1.50 and γ<sub>S</sub> = 1.15.</li>
					<li>If the engineer enters a manual c<sub>nom</sub> below the recommended value, the app keeps it but issues a warning.</li>
					<li>For fire design, a separate c<sub>min,fire</sub> from EN 1992-1-2 may govern. That route is outside the current screen.</li>
					<li>Concrete composition requirements for XF/XA exposure classes remain an engineer check outside the current app.</li>
				</ul>
			</section>

			<section id="spacing" class="doc-card">
				<p class="section-label">Practical translation</p>
				<h2>11. From required steel area to bars per meter or bar spacing</h2>
				<p>
					The public output is an area per meter width. Structural detailing requires translating
					that area into a bar diameter and spacing, or into a number of bars per meter. For a
					chosen bar diameter φ, the single-bar area is fixed and the spacing follows directly.
				</p>
				<div class="equations">
					<div class="formula">A<sub>bar</sub> = π φ<sup>2</sup> / 4</div>
					<div class="formula">n<sub>bars/m</sub> = A<sub>s,prov</sub> / A<sub>bar</sub></div>
					<div class="formula">s = 1000 A<sub>bar</sub> / A<sub>s,prov</sub></div>
					<div class="formula">A<sub>s,prov</sub> = 1000 A<sub>bar</sub> / s</div>
				</div>
				<div class="symbols">
					<div class="symbols__title">Notation</div>
					<dl class="symbols__list">
						<div class="symbols__row">
							<dt>A<sub>bar</sub></dt>
							<dd>Area of one reinforcing bar [mm²].</dd>
						</div>
						<div class="symbols__row">
							<dt>A<sub>s,prov</sub></dt>
							<dd>Area actually provided by the chosen diameter-and-spacing arrangement for a one-meter strip [mm²/m].</dd>
						</div>
						<div class="symbols__row">
							<dt>s</dt>
							<dd>Bar spacing [mm centre-to-centre].</dd>
						</div>
					</dl>
				</div>
				<ul class="notes">
					<li>The structural design workflow should round A<sub>s,prov</sub> upward, not to the nearest nominal spacing.</li>
					<li>Spacing must still satisfy EC2 detailing limits for crack control, bond, aggregate passing, and concreting tolerances.</li>
					<li>Because the app currently sizes only one governing strip area, the engineer still needs to assign whether that steel belongs in the top or bottom zone of the slab strip.</li>
				</ul>
			</section>

			<section id="outputs" class="doc-card">
				<p class="section-label">Outputs and limitations</p>
				<h2>12. Reported quantities and boundaries of validity</h2>
				<p>
					The public output is an indicative tension reinforcement area per meter width consistent
					with the section’s moment capacity under the assumed plane-section and EC2 material laws.
					It is a structural-geotechnical screening quantity and is explicitly not a substitute for
					a full structural design workflow.
				</p>
				<ul class="notes">
					<li>No bar schedule, no two-dimensional layout, no detailing at openings or supports.</li>
					<li>The current route sizes reinforcement from |M<sub>ULS,max</sub>| only; it does not yet resolve separate top and bottom reinforcement zones from the sign of the strip moment field.</li>
					<li>Serviceability verifications (crack width w<sub>k</sub>, deflection, stress limitation) are outside this route.</li>
					<li>Shear, punching, torsion, fatigue, and anchorage checks are outside this route.</li>
					<li>Compression reinforcement is not sized; the app warns once μ exceeds about 0.295 rather than auto-sizing A′<sub>s</sub>.</li>
					<li>The current public route assumes a rectangular strip section only. Flanged T-sections, ribbed slabs, and orthotropic plate reinforcement are outside this screen.</li>
					<li>The underlying specification anchor is <a href="/docs/full">the full technical specification</a>.</li>
				</ul>
			</section>

			<section id="references" class="doc-card">
				<p class="section-label">References</p>
				<h2>References</h2>
				<ul class="notes">
					<li>EN 1992-1-1:2004+A1:2014 — Eurocode 2: Design of concrete structures. Part 1-1: General rules. §3.1, §3.2, §6.1, §9.2.1.</li>
					<li>NBN EN 1992-1-1 ANB:2010 — Belgian National Annex to Eurocode 2.</li>
					<li>EN 1990:2002+A1:2005 — Basis of structural design (partial factors).</li>
					<li>fib Model Code for Concrete Structures 2010 — background for the parabola–rectangle law and the rectangular block derivation.</li>
				</ul>
			</section>
		</main>
	</div>
</div>
